In [1]:
import numpy as np

In [2]:
A = np.array([[3, 1, 1], [1, -2, -1], [1, 1, 1]])
print(A)
print(np.shape(A))

[[ 3  1  1]
 [ 1 -2 -1]
 [ 1  1  1]]
(3, 3)


In [3]:
b = np.array([4, 1, 2])
print(b)
print(np.shape(b))

[4 1 2]
(3,)


In [4]:
A_inv = np.linalg.inv(A)
print(A_inv)
print(np.shape(A_inv))

[[ 5.00000000e-01 -7.40148683e-17 -5.00000000e-01]
 [ 1.00000000e+00 -1.00000000e+00 -2.00000000e+00]
 [-1.50000000e+00  1.00000000e+00  3.50000000e+00]]
(3, 3)


In [5]:
# x = np.matmul(A_inv, b)
x = A_inv @ b
print(x)
print(np.shape(x))

[ 1. -1.  2.]
(3,)


In [8]:
#bb = np.matmul(A, x)
bb = A @ x
print(np.shape(bb))
print(bb)

if np.linalg.norm(b - bb)< 1e-3:
    print('OK')
else:
    print('something wrong')

(3,)
[4. 1. 2.]
OK
