In [1]:
import numpy as np

In [5]:
x = np.array([1, 2, 3])
c = 5

print('더하기 : {}'.format(x + c))
print('빼기 : {}'.format(x - c))
print('곱하기 : {}'.format(x * c))
print('나누기 : {}'.format(x / c))

더하기 : [6 7 8]
빼기 : [-4 -3 -2]
곱하기 : [ 5 10 15]
나누기 : [0.2 0.4 0.6]


In [17]:
y = np.array([1, 3, 5])
z = np.array([2, 9, 20])

print('더하기 : {}'.format(y + z))
print('빼기 : {}'.format(y - z))
print('곱하기 : {}'.format(y * z))
print('나누기 : {}'.format(y / z))

더하기 : [ 3 12 25]
빼기 : [ -1  -6 -15]
곱하기 : [  2  27 100]
나누기 : [0.5        0.33333333 0.25      ]


In [20]:
W = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(W[0,0])
print(W[2,3])
print(W)

1
12
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
W = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
# get 2,3 6,7
print(W[0:2,1:3])
print(W[1,1:3])
print(W[0:2,])

[[2 3]
 [6 7]]
[6 7]
[[1 2 3 4]
 [5 6 7 8]]


Array Broadcasting

In [36]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
x = np.array([0, 1, 0])
x = x[:, None]
print(x)
print(a+x)

[[0]
 [1]
 [0]]
[[1 2 3]
 [5 6 7]
 [7 8 9]]


In [39]:
y = np.array([0, 1, -1])

print(a * y)

[[ 0  2 -3]
 [ 0  5 -6]
 [ 0  8 -9]]


In [40]:
t = np.array([1,2,3])
t = t[:, None]
u = np.array([2, 0, -2])
print(t + u)

[[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]
