<a href="https://colab.research.google.com/github/rapsby/programmers/blob/main/notebook/numpy_practice_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x = np.array([1, 2, 3])
c = 5

print('더하기 : {}'.format(x + c))
print('빼기 : {}'.format(x - c))
print('곱하기 : {}'.format(x * c))
print('나누기 : {}'.format(x / c))

더하기 : [6 7 8]
빼기 : [-4 -3 -2]
곱하기 : [ 5 10 15]
나누기 : [0.2 0.4 0.6]


In [ ]:
y = np.array([1, 3, 5])
z = np.array([2, 9, 20])

print('더하기 : {}'.format(y + z))
print('빼기 : {}'.format(y - z))
print('곱하기 : {}'.format(y * z))
print('나누기 : {}'.format(y / z))

더하기 : [ 3 12 25]
빼기 : [ -1  -6 -15]
곱하기 : [  2  27 100]
나누기 : [0.5        0.33333333 0.25      ]


In [ ]:
W = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(W[0,0])
print(W[2,3])
print(W)

1
12
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
W = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
# get 2,3 6,7
print(W[0:2,1:3])
print(W[1,1:3])
print(W[0:2,])

[[2 3]
 [6 7]]
[6 7]
[[1 2 3 4]
 [5 6 7 8]]


Array Broadcasting

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
x = np.array([0, 1, 0])
x = x[:, None]
print(x)
print(a+x)

[[0]
 [1]
 [0]]
[[1 2 3]
 [5 6 7]
 [7 8 9]]


In [ ]:
y = np.array([0, 1, -1])

print(a * y)

[[ 0  2 -3]
 [ 0  5 -6]
 [ 0  8 -9]]


In [ ]:
t = np.array([1,2,3])
t = t[:, None]
u = np.array([2, 0, -2])
print(t)
print(t + u)

[[1]
 [2]
 [3]]
[[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]


In [ ]:
np.zeros([3,3,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.diag([2,4])

array([[2, 0],
       [0, 4]])

In [ ]:
np.diag((1,3,5))

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [ ]:
#항등행렬
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
#행렬곱
mat_1 = np.array([[1,4],[2,3]])
mat_2 = np.array([[7,9],[0,6]])

print(mat_1.dot((mat_2)))
print(mat_1 @ mat_2)

[[ 7 33]
 [14 36]]
[[ 7 33]
 [14 36]]


In [ ]:
# trace -> main diagonal의 합
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
arr.trace()
np.eye(2, dtype=int).trace()

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

# Linear Algebra
행렬식 (determinant)

linag = Linear Algebra

In [ ]:
arr_2 = np.array([[2,3],[1,6]])
print(arr_2)
print(np.linalg.det(arr_2))

[[2 3]
 [1 6]]
9.000000000000002


In [ ]:
arr_3 = np.array([[1,4,7],[2,5,8],[3,6,9]])
print(arr_3)
print(np.linalg.det(arr_3))

[[1 4 7]
 [2 5 8]
 [3 6 9]]
0.0


# 역행렬
행렬 A에 대해 AB = BA = I를 만족하는 행렬 B=A^-I

In [ ]:
mat = np.array([[1,4],[2,3]])
print(mat)
mat_inv = np.linalg.inv(mat)
print(mat_inv)
print(mat@mat_inv)

[[1 4]
 [2 3]]
[[-0.6  0.8]
 [ 0.4 -0.2]]
[[1. 0.]
 [0. 1.]]


# 고유값과 고유벡터(eigenvalue and eigenvector)
정방행렬 A에 대해 Ax=$\lambda x$를 만족하는 상수 $\lambda$와 이에 대응하는 벡터

In [ ]:
mat = np.array([[2,0,-2],[1,1,-2],[0,0,1]])
print(mat)
np.linalg.eig(mat) # return lambda, eigenvector

[[ 2  0 -2]
 [ 1  1 -2]
 [ 0  0  1]]


(array([1., 2., 1.]),
 array([[0.        , 0.70710678, 0.89442719],
        [1.        , 0.70710678, 0.        ],
        [0.        , 0.        , 0.4472136 ]]))

Validation

In [ ]:
eig_val, eig_vec = np.linalg.eig(mat)
eig_val

array([1., 2., 1.])

In [ ]:
eig_vec

array([[0.        , 0.70710678, 0.89442719],
       [1.        , 0.70710678, 0.        ],
       [0.        , 0.        , 0.4472136 ]])

In [ ]:
mat @ eig_vec[:,0]

array([0., 1., 0.])

In [ ]:
eig_val[0] * eig_vec[:, 0]

array([0., 1., 0.])